### ISSUE TITLE
夾的發音比重

### ISSUE THREAD

**Issue by wanewang** [yjlintw/rime_zhtw_setting#1]
我自己使用感覺夾應該是二聲比較多？
目前一聲95%會導致二聲的時候夾不會出現在前面
感覺二聲調高比重似乎會比較好找字？

**Comment by yjlintw** [comment]
感謝回報,已修正
我自己好像從來沒用過一聲的夾

**Comment by yjlintw** [comment]
目前改為
二聲: 95%
一聲: 5%

如果沒有任何問題的話,將於明天close這個issue.
